<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleProductManager.Services\SimpleProductManager.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\spmIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\spmIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\i_edit-itemBlue_F12.png" />
    <Content Include="Resources\Icons\i_edit-itemBlue_F12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Resources\Icons\VSO_Cancel_16x.png" />
    <None Remove="Resources\Icons\Cancel_16x.png" />
    <Content Include="Resources\Icons\Cancel_16x.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Resources\Icons\Add_inverse_16x.png" />
    <Content Include="Resources\Icons\Add_inverse_16x.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
