// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleProductManager.Services;

#nullable disable

namespace SimpleProductServices.Migrations
{
    [DbContext(typeof(SimpleProductDatabaseContext))]
    partial class SimpleProductDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleProductManager.Services.Entities.SimpleProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid>("SimpleProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SimpleProductCategoryId");

                    b.ToTable("SimpleProducts");
                });

            modelBuilder.Entity("SimpleProductManager.Services.Entities.SimpleProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SimpleProductCategories");
                });

            modelBuilder.Entity("SimpleProductManager.Services.Entities.SimpleProduct", b =>
                {
                    b.HasOne("SimpleProductManager.Services.Entities.SimpleProductCategory", "SimpleProductCategory")
                        .WithMany("SimpleProducts")
                        .HasForeignKey("SimpleProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimpleProductCategory");
                });

            modelBuilder.Entity("SimpleProductManager.Services.Entities.SimpleProductCategory", b =>
                {
                    b.Navigation("SimpleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
